#!/bin/bash

recorrer_directorio_clean()
{
    dir=$(dir -1)

    if [ -f ./CMakeLists.txt ]; then
    	    if [ -f ./Makefile.stage ]; then
		echo "stagemod found: cleaning..."
	    	rm -r src/stage/build/
	    fi;
	    echo "clean " $(pwd)
	    make clean >& /dev/null
    else
	    for file in $dir;
	    do
		  if [ -n $file ]; then
		      if [ -d "$file" ]; then
			  cd $file
			  recorrer_directorio_clean ./
			  cd ..
		      fi;
		  fi;
	    done;
     fi;
}



recorrer_directorio_clean pwd

