/* Auto-generated by genmsg_cpp for file /home/catec/fuerte_workspace/uav/msg/Battery.msg */
#ifndef UAV_MESSAGE_BATTERY_H
#define UAV_MESSAGE_BATTERY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace uav
{
template <class ContainerAllocator>
struct Battery_ {
  typedef Battery_<ContainerAllocator> Type;

  Battery_()
  : header()
  , status(false)
  , quality(0)
  , voltage(0.0)
  , current(0.0)
  {
  }

  Battery_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , status(false)
  , quality(0)
  , voltage(0.0)
  , current(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _status_type;
  uint8_t status;

  typedef int8_t _quality_type;
  int8_t quality;

  typedef double _voltage_type;
  double voltage;

  typedef double _current_type;
  double current;


  typedef boost::shared_ptr< ::uav::Battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav::Battery_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Battery
typedef  ::uav::Battery_<std::allocator<void> > Battery;

typedef boost::shared_ptr< ::uav::Battery> BatteryPtr;
typedef boost::shared_ptr< ::uav::Battery const> BatteryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::uav::Battery_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::uav::Battery_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace uav

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::uav::Battery_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::uav::Battery_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::uav::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b51e0ff001bdf5fd3494f40a6735b1b8";
  }

  static const char* value(const  ::uav::Battery_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb51e0ff001bdf5fdULL;
  static const uint64_t static_value2 = 0x3494f40a6735b1b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uav/Battery";
  }

  static const char* value(const  ::uav::Battery_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::uav::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool status\n\
byte quality\n\
float64 voltage\n\
float64 current\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::uav::Battery_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::uav::Battery_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::uav::Battery_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::uav::Battery_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.status);
    stream.next(m.quality);
    stream.next(m.voltage);
    stream.next(m.current);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Battery_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav::Battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::uav::Battery_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "quality: ";
    Printer<int8_t>::stream(s, indent + "  ", v.quality);
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGE_BATTERY_H

