/* Auto-generated by genmsg_cpp for file /home/catec/fuerte_workspace/uav/msg/CommandFlags.msg */
#ifndef UAV_MESSAGE_COMMANDFLAGS_H
#define UAV_MESSAGE_COMMANDFLAGS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace uav
{
template <class ContainerAllocator>
struct CommandFlags_ {
  typedef CommandFlags_<ContainerAllocator> Type;

  CommandFlags_()
  : header()
  , flags()
  {
    flags.assign(false);
  }

  CommandFlags_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , flags()
  {
    flags.assign(false);
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef boost::array<uint8_t, 8>  _flags_type;
  boost::array<uint8_t, 8>  flags;


  typedef boost::shared_ptr< ::uav::CommandFlags_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav::CommandFlags_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CommandFlags
typedef  ::uav::CommandFlags_<std::allocator<void> > CommandFlags;

typedef boost::shared_ptr< ::uav::CommandFlags> CommandFlagsPtr;
typedef boost::shared_ptr< ::uav::CommandFlags const> CommandFlagsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::uav::CommandFlags_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::uav::CommandFlags_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace uav

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::uav::CommandFlags_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::uav::CommandFlags_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::uav::CommandFlags_<ContainerAllocator> > {
  static const char* value() 
  {
    return "477052cb4fa5501822d3a6618109ce30";
  }

  static const char* value(const  ::uav::CommandFlags_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x477052cb4fa55018ULL;
  static const uint64_t static_value2 = 0x22d3a6618109ce30ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav::CommandFlags_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uav/CommandFlags";
  }

  static const char* value(const  ::uav::CommandFlags_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::uav::CommandFlags_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool[8] flags\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::uav::CommandFlags_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::uav::CommandFlags_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::uav::CommandFlags_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::uav::CommandFlags_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.flags);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CommandFlags_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav::CommandFlags_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::uav::CommandFlags_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "flags[]" << std::endl;
    for (size_t i = 0; i < v.flags.size(); ++i)
    {
      s << indent << "  flags[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.flags[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGE_COMMANDFLAGS_H

