/* Auto-generated by genmsg_cpp for file /home/catec/fuerte_workspace/uav/msg/Error.msg */
#ifndef UAV_MESSAGE_ERROR_H
#define UAV_MESSAGE_ERROR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace uav
{
template <class ContainerAllocator>
struct Error_ {
  typedef Error_<ContainerAllocator> Type;

  Error_()
  : header()
  , level(0)
  , errorMessage()
  {
  }

  Error_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , level(0)
  , errorMessage(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int8_t _level_type;
  int8_t level;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _errorMessage_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  errorMessage;

  enum { WARNING = 0 };
  enum { IMPORTANT = 1 };
  enum { CRITICAL = 2 };

  typedef boost::shared_ptr< ::uav::Error_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav::Error_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Error
typedef  ::uav::Error_<std::allocator<void> > Error;

typedef boost::shared_ptr< ::uav::Error> ErrorPtr;
typedef boost::shared_ptr< ::uav::Error const> ErrorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::uav::Error_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::uav::Error_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace uav

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::uav::Error_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::uav::Error_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::uav::Error_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3d0c13397c6a13e46fb83640aa6536ea";
  }

  static const char* value(const  ::uav::Error_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3d0c13397c6a13e4ULL;
  static const uint64_t static_value2 = 0x6fb83640aa6536eaULL;
};

template<class ContainerAllocator>
struct DataType< ::uav::Error_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uav/Error";
  }

  static const char* value(const  ::uav::Error_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::uav::Error_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int8 level\n\
int8 WARNING=0\n\
int8 IMPORTANT=1\n\
int8 CRITICAL=2\n\
string errorMessage\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::uav::Error_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::uav::Error_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::uav::Error_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::uav::Error_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.level);
    stream.next(m.errorMessage);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Error_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav::Error_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::uav::Error_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "level: ";
    Printer<int8_t>::stream(s, indent + "  ", v.level);
    s << indent << "errorMessage: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.errorMessage);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGE_ERROR_H

