/* Auto-generated by genmsg_cpp for file /home/catec/fuerte_workspace/uav/msg/Goal.msg */
#ifndef UAV_MESSAGE_GOAL_H
#define UAV_MESSAGE_GOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/Point.h"

namespace uav
{
template <class ContainerAllocator>
struct Goal_ {
  typedef Goal_<ContainerAllocator> Type;

  Goal_()
  : gohere()
  {
  }

  Goal_(const ContainerAllocator& _alloc)
  : gohere(_alloc)
  {
  }

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _gohere_type;
   ::geometry_msgs::Point_<ContainerAllocator>  gohere;


  typedef boost::shared_ptr< ::uav::Goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav::Goal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Goal
typedef  ::uav::Goal_<std::allocator<void> > Goal;

typedef boost::shared_ptr< ::uav::Goal> GoalPtr;
typedef boost::shared_ptr< ::uav::Goal const> GoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::uav::Goal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::uav::Goal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace uav

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::uav::Goal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::uav::Goal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::uav::Goal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c527f0c1d56ca8c26b7f7328f878a602";
  }

  static const char* value(const  ::uav::Goal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc527f0c1d56ca8c2ULL;
  static const uint64_t static_value2 = 0x6b7f7328f878a602ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav::Goal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uav/Goal";
  }

  static const char* value(const  ::uav::Goal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::uav::Goal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/Point gohere\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::uav::Goal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::uav::Goal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::uav::Goal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.gohere);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Goal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav::Goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::uav::Goal_<ContainerAllocator> & v) 
  {
    s << indent << "gohere: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.gohere);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGE_GOAL_H

