/* Auto-generated by genmsg_cpp for file /home/catec/fuerte_workspace/uav/msg/Monitor.msg */
#ifndef UAV_MESSAGE_MONITOR_H
#define UAV_MESSAGE_MONITOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/PoseWithCovariance.h"
#include "geometry_msgs/TwistWithCovariance.h"

namespace uav
{
template <class ContainerAllocator>
struct Monitor_ {
  typedef Monitor_<ContainerAllocator> Type;

  Monitor_()
  : header()
  , pos_status(false)
  , vel_status(false)
  , act_status(false)
  , quality(0)
  , pose()
  , twist()
  , bat_voltage(0.0)
  , bat_current(0.0)
  {
  }

  Monitor_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , pos_status(false)
  , vel_status(false)
  , act_status(false)
  , quality(0)
  , pose(_alloc)
  , twist(_alloc)
  , bat_voltage(0.0)
  , bat_current(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _pos_status_type;
  uint8_t pos_status;

  typedef uint8_t _vel_status_type;
  uint8_t vel_status;

  typedef uint8_t _act_status_type;
  uint8_t act_status;

  typedef int8_t _quality_type;
  int8_t quality;

  typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _pose_type;
   ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  pose;

  typedef  ::geometry_msgs::TwistWithCovariance_<ContainerAllocator>  _twist_type;
   ::geometry_msgs::TwistWithCovariance_<ContainerAllocator>  twist;

  typedef double _bat_voltage_type;
  double bat_voltage;

  typedef double _bat_current_type;
  double bat_current;


  typedef boost::shared_ptr< ::uav::Monitor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav::Monitor_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Monitor
typedef  ::uav::Monitor_<std::allocator<void> > Monitor;

typedef boost::shared_ptr< ::uav::Monitor> MonitorPtr;
typedef boost::shared_ptr< ::uav::Monitor const> MonitorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::uav::Monitor_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::uav::Monitor_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace uav

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::uav::Monitor_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::uav::Monitor_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::uav::Monitor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "751ee931a99632c134e9dfb1e9a2128d";
  }

  static const char* value(const  ::uav::Monitor_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x751ee931a99632c1ULL;
  static const uint64_t static_value2 = 0x34e9dfb1e9a2128dULL;
};

template<class ContainerAllocator>
struct DataType< ::uav::Monitor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uav/Monitor";
  }

  static const char* value(const  ::uav::Monitor_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::uav::Monitor_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool pos_status\n\
bool vel_status\n\
bool act_status\n\
byte quality\n\
geometry_msgs/PoseWithCovariance pose\n\
geometry_msgs/TwistWithCovariance twist\n\
float64 bat_voltage\n\
float64 bat_current\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovariance\n\
# This expresses velocity in free space with uncertianty.\n\
\n\
Twist twist\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into it's linear and angular parts. \n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::uav::Monitor_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::uav::Monitor_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::uav::Monitor_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::uav::Monitor_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.pos_status);
    stream.next(m.vel_status);
    stream.next(m.act_status);
    stream.next(m.quality);
    stream.next(m.pose);
    stream.next(m.twist);
    stream.next(m.bat_voltage);
    stream.next(m.bat_current);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Monitor_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav::Monitor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::uav::Monitor_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pos_status);
    s << indent << "vel_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vel_status);
    s << indent << "act_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.act_status);
    s << indent << "quality: ";
    Printer<int8_t>::stream(s, indent + "  ", v.quality);
    s << indent << "pose: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "twist: ";
s << std::endl;
    Printer< ::geometry_msgs::TwistWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    s << indent << "bat_voltage: ";
    Printer<double>::stream(s, indent + "  ", v.bat_voltage);
    s << indent << "bat_current: ";
    Printer<double>::stream(s, indent + "  ", v.bat_current);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGE_MONITOR_H

