/* Auto-generated by genmsg_cpp for file /home/catec/fuerte_workspace/uav/msg/Path.msg */
#ifndef UAV_MESSAGE_PATH_H
#define UAV_MESSAGE_PATH_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/Point.h"

namespace uav
{
template <class ContainerAllocator>
struct Path_ {
  typedef Path_<ContainerAllocator> Type;

  Path_()
  : n(0)
  , points()
  {
  }

  Path_(const ContainerAllocator& _alloc)
  : n(0)
  , points(_alloc)
  {
  }

  typedef uint8_t _n_type;
  uint8_t n;

  typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _points_type;
  std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  points;


  typedef boost::shared_ptr< ::uav::Path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav::Path_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Path
typedef  ::uav::Path_<std::allocator<void> > Path;

typedef boost::shared_ptr< ::uav::Path> PathPtr;
typedef boost::shared_ptr< ::uav::Path const> PathConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::uav::Path_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::uav::Path_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace uav

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::uav::Path_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::uav::Path_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::uav::Path_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7ab553daa344992075bf9c3d825d6679";
  }

  static const char* value(const  ::uav::Path_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7ab553daa3449920ULL;
  static const uint64_t static_value2 = 0x75bf9c3d825d6679ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav::Path_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uav/Path";
  }

  static const char* value(const  ::uav::Path_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::uav::Path_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 n\n\
geometry_msgs/Point[] points\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::uav::Path_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::uav::Path_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.n);
    stream.next(m.points);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Path_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav::Path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::uav::Path_<ContainerAllocator> & v) 
  {
    s << indent << "n: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.n);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGE_PATH_H

