/* Auto-generated by genmsg_cpp for file /home/catec/fuerte_workspace/uav/msg/Position.msg */
#ifndef UAV_MESSAGE_POSITION_H
#define UAV_MESSAGE_POSITION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Point.h"

namespace uav
{
template <class ContainerAllocator>
struct Position_ {
  typedef Position_<ContainerAllocator> Type;

  Position_()
  : header()
  , status(false)
  , quality(0)
  , position()
  {
  }

  Position_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , status(false)
  , quality(0)
  , position(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _status_type;
  uint8_t status;

  typedef int8_t _quality_type;
  int8_t quality;

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
   ::geometry_msgs::Point_<ContainerAllocator>  position;


  typedef boost::shared_ptr< ::uav::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav::Position_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Position
typedef  ::uav::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::uav::Position> PositionPtr;
typedef boost::shared_ptr< ::uav::Position const> PositionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::uav::Position_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::uav::Position_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace uav

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::uav::Position_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::uav::Position_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::uav::Position_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c0443ae16046ba50f772da06fb90ce25";
  }

  static const char* value(const  ::uav::Position_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc0443ae16046ba50ULL;
  static const uint64_t static_value2 = 0xf772da06fb90ce25ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav::Position_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uav/Position";
  }

  static const char* value(const  ::uav::Position_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::uav::Position_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool status\n\
byte quality\n\
geometry_msgs/Point position\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::uav::Position_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::uav::Position_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::uav::Position_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::uav::Position_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.status);
    stream.next(m.quality);
    stream.next(m.position);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Position_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::uav::Position_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "quality: ";
    Printer<int8_t>::stream(s, indent + "  ", v.quality);
    s << indent << "position: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGE_POSITION_H

