/* Auto-generated by genmsg_cpp for file /home/catec/fuerte_workspace/uav/msg/Rotation.msg */
#ifndef UAV_MESSAGE_ROTATION_H
#define UAV_MESSAGE_ROTATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Vector3.h"

namespace uav
{
template <class ContainerAllocator>
struct Rotation_ {
  typedef Rotation_<ContainerAllocator> Type;

  Rotation_()
  : header()
  , status(false)
  , quality(0)
  , rotation()
  {
  }

  Rotation_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , status(false)
  , quality(0)
  , rotation(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _status_type;
  uint8_t status;

  typedef int8_t _quality_type;
  int8_t quality;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rotation_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  rotation;


  typedef boost::shared_ptr< ::uav::Rotation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav::Rotation_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Rotation
typedef  ::uav::Rotation_<std::allocator<void> > Rotation;

typedef boost::shared_ptr< ::uav::Rotation> RotationPtr;
typedef boost::shared_ptr< ::uav::Rotation const> RotationConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::uav::Rotation_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::uav::Rotation_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace uav

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::uav::Rotation_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::uav::Rotation_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::uav::Rotation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "467f1f2fc6dfd8b94cb8b38591341219";
  }

  static const char* value(const  ::uav::Rotation_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x467f1f2fc6dfd8b9ULL;
  static const uint64_t static_value2 = 0x4cb8b38591341219ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav::Rotation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uav/Rotation";
  }

  static const char* value(const  ::uav::Rotation_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::uav::Rotation_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
bool status\n\
byte quality\n\
geometry_msgs/Vector3 rotation\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::uav::Rotation_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::uav::Rotation_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::uav::Rotation_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::uav::Rotation_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.status);
    stream.next(m.quality);
    stream.next(m.rotation);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Rotation_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav::Rotation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::uav::Rotation_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "quality: ";
    Printer<int8_t>::stream(s, indent + "  ", v.quality);
    s << indent << "rotation: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rotation);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGE_ROTATION_H

