/* Auto-generated by genmsg_cpp for file /home/catec/fuerte_workspace/uav/msg/Space_Configuration.msg */
#ifndef UAV_MESSAGE_SPACE_CONFIGURATION_H
#define UAV_MESSAGE_SPACE_CONFIGURATION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Vector3.h"

namespace uav
{
template <class ContainerAllocator>
struct Space_Configuration_ {
  typedef Space_Configuration_<ContainerAllocator> Type;

  Space_Configuration_()
  : header()
  , scalar()
  , northAngle(0.0)
  , utmLongitude(0.0)
  , utmLatitude(0.0)
  , utmHeight(0.0)
  {
  }

  Space_Configuration_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , scalar(_alloc)
  , northAngle(0.0)
  , utmLongitude(0.0)
  , utmLatitude(0.0)
  , utmHeight(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _scalar_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  scalar;

  typedef double _northAngle_type;
  double northAngle;

  typedef double _utmLongitude_type;
  double utmLongitude;

  typedef double _utmLatitude_type;
  double utmLatitude;

  typedef double _utmHeight_type;
  double utmHeight;


  typedef boost::shared_ptr< ::uav::Space_Configuration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav::Space_Configuration_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Space_Configuration
typedef  ::uav::Space_Configuration_<std::allocator<void> > Space_Configuration;

typedef boost::shared_ptr< ::uav::Space_Configuration> Space_ConfigurationPtr;
typedef boost::shared_ptr< ::uav::Space_Configuration const> Space_ConfigurationConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::uav::Space_Configuration_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::uav::Space_Configuration_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace uav

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::uav::Space_Configuration_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::uav::Space_Configuration_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::uav::Space_Configuration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b4122defdaa459823c428e4bcf09d468";
  }

  static const char* value(const  ::uav::Space_Configuration_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb4122defdaa45982ULL;
  static const uint64_t static_value2 = 0x3c428e4bcf09d468ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav::Space_Configuration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uav/Space_Configuration";
  }

  static const char* value(const  ::uav::Space_Configuration_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::uav::Space_Configuration_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
geometry_msgs/Vector3 scalar\n\
float64 northAngle\n\
float64 utmLongitude\n\
float64 utmLatitude\n\
float64 utmHeight\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::uav::Space_Configuration_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::uav::Space_Configuration_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::uav::Space_Configuration_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::uav::Space_Configuration_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.scalar);
    stream.next(m.northAngle);
    stream.next(m.utmLongitude);
    stream.next(m.utmLatitude);
    stream.next(m.utmHeight);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Space_Configuration_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav::Space_Configuration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::uav::Space_Configuration_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "scalar: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.scalar);
    s << indent << "northAngle: ";
    Printer<double>::stream(s, indent + "  ", v.northAngle);
    s << indent << "utmLongitude: ";
    Printer<double>::stream(s, indent + "  ", v.utmLongitude);
    s << indent << "utmLatitude: ";
    Printer<double>::stream(s, indent + "  ", v.utmLatitude);
    s << indent << "utmHeight: ";
    Printer<double>::stream(s, indent + "  ", v.utmHeight);
  }
};


} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGE_SPACE_CONFIGURATION_H

