#goal definition
time download_window
---
#result definition
uint8   total_images_sent
uint32  total_bytes_sent
uint8   remaining_images
uint32  remaining_bytes
---
#feedback definition
uint8  images_sent
uint32 bytes_sent
