"""autogenerated by genpy from catec_actions_msgs/DownloadDataGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class DownloadDataGoal(genpy.Message):
  _md5sum = "97c0d2c9554172814a42542fe0ff72cf"
  _type = "catec_actions_msgs/DownloadDataGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
time download_window

"""
  __slots__ = ['download_window']
  _slot_types = ['time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       download_window

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DownloadDataGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.download_window is None:
        self.download_window = genpy.Time()
    else:
      self.download_window = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2I.pack(_x.download_window.secs, _x.download_window.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.download_window is None:
        self.download_window = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.download_window.secs, _x.download_window.nsecs,) = _struct_2I.unpack(str[start:end])
      self.download_window.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2I.pack(_x.download_window.secs, _x.download_window.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.download_window is None:
        self.download_window = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.download_window.secs, _x.download_window.nsecs,) = _struct_2I.unpack(str[start:end])
      self.download_window.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2I = struct.Struct("<2I")
