"""autogenerated by genpy from catec_actions_msgs/GoToWayPointsResult.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import catec_msgs.msg
import std_msgs.msg

class GoToWayPointsResult(genpy.Message):
  _md5sum = "ff6341b1ea48ec4091a1b3f7672094cc"
  _type = "catec_actions_msgs/GoToWayPointsResult"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#reult definition
catec_msgs/PositionWithCheckStamped final_position

================================================================================
MSG: catec_msgs/PositionWithCheckStamped
Header header
PositionWithCheck position
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: catec_msgs/PositionWithCheck
float64 x
float64 y
float64 z
uint8 valid
"""
  __slots__ = ['final_position']
  _slot_types = ['catec_msgs/PositionWithCheckStamped']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       final_position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GoToWayPointsResult, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.final_position is None:
        self.final_position = catec_msgs.msg.PositionWithCheckStamped()
    else:
      self.final_position = catec_msgs.msg.PositionWithCheckStamped()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.final_position.header.seq, _x.final_position.header.stamp.secs, _x.final_position.header.stamp.nsecs))
      _x = self.final_position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3dB.pack(_x.final_position.position.x, _x.final_position.position.y, _x.final_position.position.z, _x.final_position.position.valid))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.final_position is None:
        self.final_position = catec_msgs.msg.PositionWithCheckStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.final_position.header.seq, _x.final_position.header.stamp.secs, _x.final_position.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.final_position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.final_position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 25
      (_x.final_position.position.x, _x.final_position.position.y, _x.final_position.position.z, _x.final_position.position.valid,) = _struct_3dB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.final_position.header.seq, _x.final_position.header.stamp.secs, _x.final_position.header.stamp.nsecs))
      _x = self.final_position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3dB.pack(_x.final_position.position.x, _x.final_position.position.y, _x.final_position.position.z, _x.final_position.position.valid))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.final_position is None:
        self.final_position = catec_msgs.msg.PositionWithCheckStamped()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.final_position.header.seq, _x.final_position.header.stamp.secs, _x.final_position.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.final_position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.final_position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 25
      (_x.final_position.position.x, _x.final_position.position.y, _x.final_position.position.z, _x.final_position.position.valid,) = _struct_3dB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_3dB = struct.Struct("<3dB")
