#!/bin/bash

recorrer_directorio_clean()
{
    dir=$(dir -1)

    if [ -f ./CMakeLists.txt ]; then
	    echo "rosmake " $(pwd)
	    rosmake 
    else
	    for file in $dir;
	    do
		  if [ -n $file ]; then
		      if [ -d "$file" ]; then
			  cd $file
			  recorrer_directorio_clean ./
			  cd ..
		      fi;
		  fi;
	    done;
     fi;
}



recorrer_directorio_clean pwd

