"""autogenerated by genpy from catec_msgs/AALControlReferenceStamped.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import catec_msgs.msg
import std_msgs.msg

class AALControlReferenceStamped(genpy.Message):
  _md5sum = "8d6b2dfe261a46b1146837f3e560683d"
  _type = "catec_msgs/AALControlReferenceStamped"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
AALControlReference control_reference


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: catec_msgs/AALControlReference
uint8 POSITION=1
uint8 ANGLES=2
uint8 mode
Position final_effector_position
Orientation final_effector_orientation
float64    claw
float64[6] joints_angles



================================================================================
MSG: catec_msgs/Position
float64 x
float64 y
float64 z
================================================================================
MSG: catec_msgs/Orientation
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','control_reference']
  _slot_types = ['std_msgs/Header','catec_msgs/AALControlReference']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,control_reference

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AALControlReferenceStamped, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.control_reference is None:
        self.control_reference = catec_msgs.msg.AALControlReference()
    else:
      self.header = std_msgs.msg.Header()
      self.control_reference = catec_msgs.msg.AALControlReference()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_B7d.pack(_x.control_reference.mode, _x.control_reference.final_effector_position.x, _x.control_reference.final_effector_position.y, _x.control_reference.final_effector_position.z, _x.control_reference.final_effector_orientation.x, _x.control_reference.final_effector_orientation.y, _x.control_reference.final_effector_orientation.z, _x.control_reference.claw))
      buff.write(_struct_6d.pack(*self.control_reference.joints_angles))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.control_reference is None:
        self.control_reference = catec_msgs.msg.AALControlReference()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.control_reference.mode, _x.control_reference.final_effector_position.x, _x.control_reference.final_effector_position.y, _x.control_reference.final_effector_position.z, _x.control_reference.final_effector_orientation.x, _x.control_reference.final_effector_orientation.y, _x.control_reference.final_effector_orientation.z, _x.control_reference.claw,) = _struct_B7d.unpack(str[start:end])
      start = end
      end += 48
      self.control_reference.joints_angles = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_B7d.pack(_x.control_reference.mode, _x.control_reference.final_effector_position.x, _x.control_reference.final_effector_position.y, _x.control_reference.final_effector_position.z, _x.control_reference.final_effector_orientation.x, _x.control_reference.final_effector_orientation.y, _x.control_reference.final_effector_orientation.z, _x.control_reference.claw))
      buff.write(self.control_reference.joints_angles.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.control_reference is None:
        self.control_reference = catec_msgs.msg.AALControlReference()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.control_reference.mode, _x.control_reference.final_effector_position.x, _x.control_reference.final_effector_position.y, _x.control_reference.final_effector_position.z, _x.control_reference.final_effector_orientation.x, _x.control_reference.final_effector_orientation.y, _x.control_reference.final_effector_orientation.z, _x.control_reference.claw,) = _struct_B7d.unpack(str[start:end])
      start = end
      end += 48
      self.control_reference.joints_angles = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=6)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6d = struct.Struct("<6d")
_struct_3I = struct.Struct("<3I")
_struct_B7d = struct.Struct("<B7d")
