"""autogenerated by genpy from catec_msgs/Obstacle.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import catec_msgs.msg

class Obstacle(genpy.Message):
  _md5sum = "65b2eb41fd50368a9d7df323563b68e1"
  _type = "catec_msgs/Obstacle"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Position pos
Vector3  size



================================================================================
MSG: catec_msgs/Position
float64 x
float64 y
float64 z
================================================================================
MSG: catec_msgs/Vector3
float64 x
float64 y
float64 z
"""
  __slots__ = ['pos','size']
  _slot_types = ['catec_msgs/Position','catec_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pos,size

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Obstacle, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pos is None:
        self.pos = catec_msgs.msg.Position()
      if self.size is None:
        self.size = catec_msgs.msg.Vector3()
    else:
      self.pos = catec_msgs.msg.Position()
      self.size = catec_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.pos.x, _x.pos.y, _x.pos.z, _x.size.x, _x.size.y, _x.size.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pos is None:
        self.pos = catec_msgs.msg.Position()
      if self.size is None:
        self.size = catec_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.pos.x, _x.pos.y, _x.pos.z, _x.size.x, _x.size.y, _x.size.z,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.pos.x, _x.pos.y, _x.pos.z, _x.size.x, _x.size.y, _x.size.z))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pos is None:
        self.pos = catec_msgs.msg.Position()
      if self.size is None:
        self.size = catec_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.pos.x, _x.pos.y, _x.pos.z, _x.size.x, _x.size.y, _x.size.z,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6d = struct.Struct("<6d")
