"""autogenerated by genpy from catec_msgs/PathWithCruise.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import catec_msgs.msg

class PathWithCruise(genpy.Message):
  _md5sum = "33d82206e4232e221fdbef3af4a4f39c"
  _type = "catec_msgs/PathWithCruise"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """WayPointWithCruise[] wp
================================================================================
MSG: catec_msgs/WayPointWithCruise
float64 x
float64 y
float64 z
float32 cruise
float64 heading
"""
  __slots__ = ['wp']
  _slot_types = ['catec_msgs/WayPointWithCruise[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       wp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PathWithCruise, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.wp is None:
        self.wp = []
    else:
      self.wp = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.wp)
      buff.write(_struct_I.pack(length))
      for val1 in self.wp:
        _x = val1
        buff.write(_struct_3dfd.pack(_x.x, _x.y, _x.z, _x.cruise, _x.heading))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.wp is None:
        self.wp = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.wp = []
      for i in range(0, length):
        val1 = catec_msgs.msg.WayPointWithCruise()
        _x = val1
        start = end
        end += 36
        (_x.x, _x.y, _x.z, _x.cruise, _x.heading,) = _struct_3dfd.unpack(str[start:end])
        self.wp.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.wp)
      buff.write(_struct_I.pack(length))
      for val1 in self.wp:
        _x = val1
        buff.write(_struct_3dfd.pack(_x.x, _x.y, _x.z, _x.cruise, _x.heading))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.wp is None:
        self.wp = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.wp = []
      for i in range(0, length):
        val1 = catec_msgs.msg.WayPointWithCruise()
        _x = val1
        start = end
        end += 36
        (_x.x, _x.y, _x.z, _x.cruise, _x.heading,) = _struct_3dfd.unpack(str[start:end])
        self.wp.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3dfd = struct.Struct("<3dfd")
