"""autogenerated by genpy from catec_msgs/PositionControlParameters.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PositionControlParameters(genpy.Message):
  _md5sum = "4c0a96c962b78df5e0ce5b434936e2cc"
  _type = "catec_msgs/PositionControlParameters"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 pid
float64 Kp
float64 Ki
float64 Kd
float64 i_min
float64 i_max
float64 max_velocity


"""
  __slots__ = ['pid','Kp','Ki','Kd','i_min','i_max','max_velocity']
  _slot_types = ['int32','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pid,Kp,Ki,Kd,i_min,i_max,max_velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PositionControlParameters, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pid is None:
        self.pid = 0
      if self.Kp is None:
        self.Kp = 0.
      if self.Ki is None:
        self.Ki = 0.
      if self.Kd is None:
        self.Kd = 0.
      if self.i_min is None:
        self.i_min = 0.
      if self.i_max is None:
        self.i_max = 0.
      if self.max_velocity is None:
        self.max_velocity = 0.
    else:
      self.pid = 0
      self.Kp = 0.
      self.Ki = 0.
      self.Kd = 0.
      self.i_min = 0.
      self.i_max = 0.
      self.max_velocity = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_i6d.pack(_x.pid, _x.Kp, _x.Ki, _x.Kd, _x.i_min, _x.i_max, _x.max_velocity))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 52
      (_x.pid, _x.Kp, _x.Ki, _x.Kd, _x.i_min, _x.i_max, _x.max_velocity,) = _struct_i6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_i6d.pack(_x.pid, _x.Kp, _x.Ki, _x.Kd, _x.i_min, _x.i_max, _x.max_velocity))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 52
      (_x.pid, _x.Kp, _x.Ki, _x.Kd, _x.i_min, _x.i_max, _x.max_velocity,) = _struct_i6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i6d = struct.Struct("<i6d")
