"""autogenerated by genpy from catec_msgs/UALState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import catec_msgs.msg

class UALState(genpy.Message):
  _md5sum = "c9002b774c1fe0eae88ac07be40ee78b"
  _type = "catec_msgs/UALState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """DynamicState dynamic_state
uint8 flying_state
uint8 remaining_battery
uint8 memory_usage
uint8 cpu_usage
================================================================================
MSG: catec_msgs/DynamicState
PositionWithCheck position
OrientationWithCheck orientation
VelocityWithCheck velocity
================================================================================
MSG: catec_msgs/PositionWithCheck
float64 x
float64 y
float64 z
uint8 valid
================================================================================
MSG: catec_msgs/OrientationWithCheck
float64 x
float64 y
float64 z
uint8 valid
================================================================================
MSG: catec_msgs/VelocityWithCheck
float64 x
float64 y
float64 z
uint8 valid
"""
  __slots__ = ['dynamic_state','flying_state','remaining_battery','memory_usage','cpu_usage']
  _slot_types = ['catec_msgs/DynamicState','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       dynamic_state,flying_state,remaining_battery,memory_usage,cpu_usage

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UALState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.dynamic_state is None:
        self.dynamic_state = catec_msgs.msg.DynamicState()
      if self.flying_state is None:
        self.flying_state = 0
      if self.remaining_battery is None:
        self.remaining_battery = 0
      if self.memory_usage is None:
        self.memory_usage = 0
      if self.cpu_usage is None:
        self.cpu_usage = 0
    else:
      self.dynamic_state = catec_msgs.msg.DynamicState()
      self.flying_state = 0
      self.remaining_battery = 0
      self.memory_usage = 0
      self.cpu_usage = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3dB3dB3d5B.pack(_x.dynamic_state.position.x, _x.dynamic_state.position.y, _x.dynamic_state.position.z, _x.dynamic_state.position.valid, _x.dynamic_state.orientation.x, _x.dynamic_state.orientation.y, _x.dynamic_state.orientation.z, _x.dynamic_state.orientation.valid, _x.dynamic_state.velocity.x, _x.dynamic_state.velocity.y, _x.dynamic_state.velocity.z, _x.dynamic_state.velocity.valid, _x.flying_state, _x.remaining_battery, _x.memory_usage, _x.cpu_usage))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.dynamic_state is None:
        self.dynamic_state = catec_msgs.msg.DynamicState()
      end = 0
      _x = self
      start = end
      end += 79
      (_x.dynamic_state.position.x, _x.dynamic_state.position.y, _x.dynamic_state.position.z, _x.dynamic_state.position.valid, _x.dynamic_state.orientation.x, _x.dynamic_state.orientation.y, _x.dynamic_state.orientation.z, _x.dynamic_state.orientation.valid, _x.dynamic_state.velocity.x, _x.dynamic_state.velocity.y, _x.dynamic_state.velocity.z, _x.dynamic_state.velocity.valid, _x.flying_state, _x.remaining_battery, _x.memory_usage, _x.cpu_usage,) = _struct_3dB3dB3d5B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3dB3dB3d5B.pack(_x.dynamic_state.position.x, _x.dynamic_state.position.y, _x.dynamic_state.position.z, _x.dynamic_state.position.valid, _x.dynamic_state.orientation.x, _x.dynamic_state.orientation.y, _x.dynamic_state.orientation.z, _x.dynamic_state.orientation.valid, _x.dynamic_state.velocity.x, _x.dynamic_state.velocity.y, _x.dynamic_state.velocity.z, _x.dynamic_state.velocity.valid, _x.flying_state, _x.remaining_battery, _x.memory_usage, _x.cpu_usage))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.dynamic_state is None:
        self.dynamic_state = catec_msgs.msg.DynamicState()
      end = 0
      _x = self
      start = end
      end += 79
      (_x.dynamic_state.position.x, _x.dynamic_state.position.y, _x.dynamic_state.position.z, _x.dynamic_state.position.valid, _x.dynamic_state.orientation.x, _x.dynamic_state.orientation.y, _x.dynamic_state.orientation.z, _x.dynamic_state.orientation.valid, _x.dynamic_state.velocity.x, _x.dynamic_state.velocity.y, _x.dynamic_state.velocity.z, _x.dynamic_state.velocity.valid, _x.flying_state, _x.remaining_battery, _x.memory_usage, _x.cpu_usage,) = _struct_3dB3dB3d5B.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3dB3dB3d5B = struct.Struct("<3dB3dB3d5B")
